version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: poc_circleci_buildkit_parent
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - add_ssh_keys:
          fingerprints:
            - "8f:eb:ae:12:5e:4e:f9:e2:06:0b:44:8e:07:9e:82:b3" 
      - checkout
      - setup_remote_docker:
          version: 18.09.3
          # enterprise feature - enable if you're enterprise           
          # docker_layer_caching: true
      - run:
          name: Build Docker image
          command: DOCKER_BUILDKIT=1 docker build --progress plain --ssh default=${SSH_AUTH_SOCK} -t ${DOCKER_USER}/${IMAGE_NAME} .
      - run: |
          docker login -u ${DOCKER_USER} -p ${DOCKER_HUB_TOKEN}
          docker push ${DOCKER_USER}/${IMAGE_NAME}
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
