version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: bryanhuntesl/
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - add_ssh_keys:
          fingerprints:
            - "58:25:b9:3b:e2:7c:46:89:60:26:10:9f:d0:e2:b6:ac"
            
      - checkout
      - setup_remote_docker:
          version: 18.09.3 
      - run:
          name: Build Docker image
          command: DOCKER_BUILDKIT=1 docker build --progress plain --ssh default=${SSH_AUTH_SOCK} . 
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master